### PR TITLE
Fix Dockerfile

### PR DESCRIPTION
**Pull request by STRUCTiX**
This PR fixes the docker image build.

### CODE REVIEW

**Comment by luoe** [comment]
Why do you need to copy all files in the current directory into the docker container?

**Comment by primeos** [comment]
I assume this is because the resulting container doesn't serve anything by default (or some default template - I didn't check it).

We should probably document that the container requires a volume / bind mount for the actual data, e.g.:
`--volume="$PWD:/srv/jekyll"` or maybe even better
`--mount type=bind,source=$PWD,destination=/srv/jekyll`.
We could also add a shell script or Docker Compose file for that.

**Comment by STRUCTiX** [comment]
Yes that's right. The docker image had only the Gemfile dependencies installed.

We could either rebuild the image on every change (would keep the dependencies updated) or bind the actual data with a bind mount.

**Comment by primeos** [comment]
> We could either rebuild the image on every change

We should try to avoid this as it would cause a lot of overhead (time + disk space).

> (would keep the dependencies updated)

Since we currently lock all dependencies (`Gemfile.lock`) it shouldn't make a difference.
I am however not sure if we should actually lock the dependencies (i.e. maintain a `Gemfile.lock` - it has both advantages and disadvantages).

> bind the actual data with a bind mount

IMO, that should be the way to go.

**Pull request closed without merging**
