### PR TITLE
Add References to new PO module books

### PR DESCRIPTION
**Pull request by PhictionalOne**

### CODE REVIEW

**Comment by PhictionalOne** [comment]
@luoe `_site/tools/index.html` fails the html-proofer again. That's not my fault... And the new fork doesn't have the `_site` as the `.gitignore` worked

**Comment by luoe** [comment]
There is a folder called tools where your wanted file has been all the time.

**Comment by PhictionalOne** [comment]
> There is a folder called tools where your wanted file has been all the time.

Yeah... I am stupid. Just there to change something real quick and than that annoying stuff....

**Comment by luoe** [comment]
Since when does HTMLProofer ignore links that are inside HTML comments? Good to know @primeos

**Comment by primeos** [comment]
@luoe not sure but that behaviour makes sense to me so probably for a long time. It doesn't seem to be configurable though: https://github.com/gjtorikian/html-proofer#configuration (there are lots of other options).

**Pull request merged**
