### PR TITLE
Update to WS21 stuff

### PR DESCRIPTION
**Pull request by PhictionalOne**
Some minor stuff done to Covid-FAQ and Anfiveranstaltungen.

Also added basically Hannah's Mail about new PO change.

Can be referenced to #123

### CODE REVIEW

**Comment by PhictionalOne** [comment]
Shiiiit. Thats way more commits than I wanted to PR...

**Comment by luoe** [comment]
Thank you very much. Please ensure that all links are valid, the GitHub CI got you covered with checking :)

**Comment by luoe** [comment]
Oh what, this isn't Anfiheft :D

**Comment by PhictionalOne** [comment]
> Oh what, this isn't Anfiheft :D

Yeah. I still procrastinate some stuff.

**Comment by PhictionalOne** [comment]
Regarding 05b8c5055c242f563f6695e50c0c8f872d4e4782:
The my-stuwe links could not be fixed as the site has major problems...
image

**Comment by PhictionalOne** [comment]
Ja F***ing finally....

**Pull request merged**
