### PR TITLE
Add Modulbuch references

### PR DESCRIPTION
**Pull request by PhictionalOne**
* Refer to PO 2021 / PO 2015 Modulbuch
* Add date for 'Erstibegrüßung'

### CODE REVIEW

**Comment by luoe** [comment]
Dear lord. Please remove the "Merge master of bla" commits from your PR (for example by rebasing).
Otherwise all commits will be squashed into one when merging.
(Whoever creates a merge commit with "Merger master..." commits will be banned from the fsi-tue organization.)

**Comment by PhictionalOne** [comment]
> Dear lord. Please remove the "Merge master of bla" commits from your PR (for example by rebasing). Otherwise all commits will be squashed into one when merging. (Whoever creates a merge commit with "Merger master..." commits will be banned from the fsi-tue organization.)

Wooww... I just happen to see this. Weird I rebased the pull....
I guess I kill this fork

**Comment by luoe** [comment]
And don't add any content from _site forcefully. The exclusion in .gitignore has a meaning! This is dynamically gernerated content from Jekyll.

**Comment by PhictionalOne** [comment]
> And don't add any content from _site forcefully. The exclusion in .gitignore has a meaning! This is dynamically gernerated content from Jekyll.

It is not. Its the static `/tools` And since meet.fsi.... doesn't exist anymore I have to change that. I would not have touched it if the html-proofer didn't called this out

**Comment by luoe** [comment]
See 6b3d4f7769bd354b4c93758770a124210117869a

**Pull request closed without merging**
